# Generated by Django 3.1.3 on 2022-09-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('date_of_quizz', models.DateTimeField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
