# Generated by Django 4.1 on 2022-08-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('date_of_entry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_quiz', models.DateField()),
                ('num_questions', models.IntegerField()),
                ('category', models.CharField(choices=[('NA', 'Nauka'), ('MU', 'Muzika'), ('FM', 'Film')], default='FM', max_length=2)),
                ('difficulty', models.CharField(choices=[('L', 'Lako'), ('S', 'Srednje'), ('T', 'Teško')], default='S', max_length=2)),
                ('type', models.CharField(choices=[('MC', 'Jedan od ponuđenih'), ('TF', 'Tačno/Netačno')], default='MC', max_length=2)),
                ('score', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.player')),
            ],
        ),
    ]
